// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alert } from "./Alert";
import type { Route } from "./Route";
import type { Stop } from "./Stop";

export type Import = { stops_realtime: { [key: string]: Stop }, service_alerts_realtime: Array<Alert>, routes_static: { [key: string]: Route }, };