// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Route = { route_id: string, route_name: string, route_color: string, route_text_color: string, };