// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Vehicle } from "./Vehicle";

export type Stop = { name: string, trips: Array<Vehicle>, destinations: { [key: string]: { [key: string]: Array<Vehicle> } }, };