// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Vehicle = { route_id: string, route_name: string, destination_id: string, destination_name: string, minutes_until_arrival: number, };